# Generated by Django 6.0 on 2026-02-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nombre',
        ),
    ]
