# Generated by Django 6.0 on 2026-03-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
